/* Generated By:JavaCC: Do not edit this line. JavaCompilerConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_SIMPLES = 5;
  /** RegularExpression Id. */
  int COMENTARIOS_LONGO = 6;
  /** RegularExpression Id. */
  int OBS = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int IMPORT = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int MAIN = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int STATIC = 18;
  /** RegularExpression Id. */
  int PRIVATE = 19;
  /** RegularExpression Id. */
  int PROTECTED = 20;
  /** RegularExpression Id. */
  int PUBLIC = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int ELSE_IF = 23;
  /** RegularExpression Id. */
  int ELSE = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int PRINT = 27;
  /** RegularExpression Id. */
  int INPUT = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int BREAK = 30;
  /** RegularExpression Id. */
  int CONTINUE = 31;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 32;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 33;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 34;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 35;
  /** RegularExpression Id. */
  int ABRE_COLCHETE = 36;
  /** RegularExpression Id. */
  int FECHA_COLCHETE = 37;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 38;
  /** RegularExpression Id. */
  int VIRGULA = 39;
  /** RegularExpression Id. */
  int PONTO = 40;
  /** RegularExpression Id. */
  int RECEBE = 41;
  /** RegularExpression Id. */
  int MAIOR = 42;
  /** RegularExpression Id. */
  int MENOR = 43;
  /** RegularExpression Id. */
  int NEGACAO = 44;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 45;
  /** RegularExpression Id. */
  int IGUAL = 46;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 47;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 48;
  /** RegularExpression Id. */
  int DIFERENTE = 49;
  /** RegularExpression Id. */
  int OR = 50;
  /** RegularExpression Id. */
  int AND = 51;
  /** RegularExpression Id. */
  int INCREMENTO = 52;
  /** RegularExpression Id. */
  int DECREMENTO = 53;
  /** RegularExpression Id. */
  int MAIS = 54;
  /** RegularExpression Id. */
  int MENOS = 55;
  /** RegularExpression Id. */
  int ASTERISCO = 56;
  /** RegularExpression Id. */
  int BARRA = 57;
  /** RegularExpression Id. */
  int PORCENTO = 58;
  /** RegularExpression Id. */
  int MAIS_IGUAL = 59;
  /** RegularExpression Id. */
  int MENOS_IGUAL = 60;
  /** RegularExpression Id. */
  int ASTERISCO_IGUAL = 61;
  /** RegularExpression Id. */
  int BARRA_IGUAL = 62;
  /** RegularExpression Id. */
  int PORCENTO_IGUAL = 63;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 64;
  /** RegularExpression Id. */
  int LETRA = 65;
  /** RegularExpression Id. */
  int DIGITO = 66;
  /** RegularExpression Id. */
  int TIPOS_BASICOS = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int DECIMAL = 69;
  /** RegularExpression Id. */
  int FLOATING_LITERAL = 70;
  /** RegularExpression Id. */
  int STRING_LITERAL = 71;
  /** RegularExpression Id. */
  int BOOL_LITERAL = 72;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO_SIMPLES>",
    "<COMENTARIOS_LONGO>",
    "<OBS>",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"String\"",
    "\"null\"",
    "\"import\"",
    "\"class\"",
    "\"main\"",
    "\"void\"",
    "\"return\"",
    "\"static\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"if\"",
    "\"else if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"System.out.println\"",
    "\"Scanner\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\":\"",
    "\"==\"",
    "\" >=\"",
    "\"<=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "<TIPOS_BASICOS>",
    "<INTEGER_LITERAL>",
    "<DECIMAL>",
    "<FLOATING_LITERAL>",
    "<STRING_LITERAL>",
    "<BOOL_LITERAL>",
    "\"\"",
  };

}
